# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_mybloguser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybloguser',
            name='profilepic',
            field=models.ImageField(upload_to=b'', validators=['jpeg', 'jpg', 'png']),
        ),
    ]
